### ISSUE TITLE
Contao 3.5.26

### ISSUE THREAD

**Issue by fkaminski-dev** [timgatzky/universalpayment_paypal#1]
Hallo, ich habe diese Erweiterung zufällig entdeckt und wollte dies für unsere Reitvereinsseite testen.
Die beiden Erweiterungen habe ich in das Verzeichnis system/modules kopiert, die install.php aufgerufen und Datenbank Updates durchgeführt. Ich mußte unter 3.5.26 noch über den Autoload-Creator gehen und konnte im Anschluß das Modul/Inhaltselement aufrufen. 

Wen ich jetzt eine Seite aufrufe in der das Modul o. Inhaltselement eingetragen wird erhalte ich unter Chrome einen HTTP ERROR 500. Im System Log steht:

> [05-May-2017 12:39:44 Europe/Berlin] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 65488 bytes) in C:\__WEBDEV__SITES__\rv-stjuergen\htdocs\vendor\composer\ClassLoader.php on line 321

Im Contao Forum nachgefragt unter [https://community.contao.org/de/showthread.php?66660-Cobtao-3-5-26-universalpayment_paypal](url)

Für ein Hinweise zur korrekten Vorgehensweise/Konfiguration dankbar ...
Danke
Frank

**Comment by timgatzky** [comment]
Dies ist nur das paypal Modul. Der Kern muss erstmal stehen: https://github.com/timgatzky/universalpayment

Die Erweiterung war eine Bezahlerweiterung, die in einem langen Mahnstreit endete bzw. noch drin gefangen ist. Entwicklung wird meinerseits hier derzeit nicht betrieben.
